### ISSUE TITLE
Add generic did:key resolver

### ISSUE THREAD

**Issue by TimoGlastra** [animo/aries-cloudagent-python#10]
Currently we are doing a quick ad-hoc implementation to transform Ed25519 `did:key`s to a DIDDoc.

We need to create a more generic did:key to diddoc resolver that we can also use for BLS keys and other keys that may be added in the future.

## TODO

- [ ] Add generic did:key to diddoc transformer
- [ ] Add ed25519 specific tranformer
- [ ] Add bls12381_g2 specific transformer
- [ ] [maybe] Add bls12381_g1 specific transformer
