### ISSUE TITLE
Move JSON-LD Signature code into this repo

### ISSUE THREAD

**Issue by karimStekelenburg** [animo/aries-cloudagent-python#12]
Our jsonld-signatures 'port' has been created separately from ACA-Py. Therefore we need to move it into this repo.

### TODO
- [x] Move the code into this codebase
- [x] Ensure all added dependencies are present
- [x] Update import statements regarding `wallet_util.py`
