### ISSUE TITLE
did admin routes

### ISSUE THREAD

**Issue by TimoGlastra** [animo/aries-cloudagent-python#6]
ACA-Py currently exposes multiple endpoints related to creating and retrieving DIDs. This is very specific to indy DIDs and therefore

## TODO

- [ ] Add option to create bls12381 `did:key`s
- [ ] Add option to create ed25519 `did:key`s
- [ ] Add option to retrieve dids

## Questions

- Should API be backwards compatible?
- Could integration with SICPA did resolver make this easier?

Indy DID:

```json
{
  "did": "WgWxqztrNooG92RXvxSTWv",
  "posture": "wallet_only",
  "verkey": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
}
```
